### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by ghost**
Remaining issues:
- doesn't seem to like redirects
- doesn't send a response if both backends fail

### CODE REVIEW

**Comment by ghost** [comment]
> doesn't seem to like redirects

fixed in the latest commit

> doesn't seem to like redirects

i'm not sure the canceling is completely good, and free of races. especially the select block makes me think the other backend might receive a response too just before being cancelled, and then overwrite the legitimate first response. but maybe that's okay, if both backends come up with a good response at the same time?

**Comment by whyrusleeping** [comment]
ooooh, in response to your second point. Thats a good point, and we can fix it by checking if our channel is closed after closing the other channel:

```
select {
case <-ourChannel:
default:
}
```

or something like that

**Comment by ghost** [comment]
After fixing the redirect, there was another mysterious 404 instead of redirect on `/docs/install` in combination with IpnsHostnameOption, which fixed itself by turning it off and on again.

**Comment by ghost** [comment]
RFM -- this is good to go and has been the status quo on ipfs.io for a while

**Comment by ghost** [comment]
@noffle let's rebase yours on top

**Comment by hackergrrl** [comment]
Sure; I'll take on the merge pain :)

**Comment by ghost** [comment]
> RFM -- this is good to go and has been the status quo on ipfs.io for a while

Even more good to go now :)

**Comment by whyrusleeping** [comment]
Alright, i'll merge this one now. Thanks!

**Pull request merged**
