### PR TITLE
partially buffer responses to be sure of which one to return

### PR DESCRIPTION
**Pull request by whyrusleeping**
buffer up to 16MB from each response, return the best one

### CODE REVIEW

**Comment by ghost** [comment]
LGTM :+1:

**Comment by whyrusleeping** [comment]
before merging this lets test deploying it on earth

**Comment by ghost** [comment]
Is there an upper limit on the number of buffers?

**Comment by whyrusleeping** [comment]
no, there is not. but the bufferpool manages freeing them as needed

**Pull request merged**
